<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="screenModel" nsURI="screenModel" nsPrefix="screenModel">
  <eClassifiers xsi:type="ecore:EClass" name="ScreenModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="seite" upperBound="-1"
        eType="#//Seite" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenobjekt" upperBound="-1"
        eType="#//Datenobjekt" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenstruktur" upperBound="-1"
        eType="#//Datenstruktur" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Seite">
    <eStructuralFeatures xsi:type="ecore:EReference" name="button" eType="#//Button"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateneingabe" eType="#//Dateneingabe"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenausgabe" upperBound="-1"
        eType="#//Datenausgabe" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pageName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Button">
    <eStructuralFeatures xsi:type="ecore:EReference" name="seite" eType="#//Seite"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayText" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dateneingabe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenobjekt" eType="#//Datenobjekt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dateneingabefeld" lowerBound="1"
        upperBound="-1" eType="#//Dateneingabefeld" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datenausgabe">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenobjekt" eType="#//Datenobjekt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenausgabefeld" lowerBound="1"
        upperBound="-1" eType="#//Datenausgabefeld" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datenobjekt">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datenstruktur" lowerBound="1"
        eType="#//Datenstruktur"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datenstruktur">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribute" upperBound="-1"
        eType="#//Attribut" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Attribut">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="datentyp" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datenausgabefeld">
    <eStructuralFeatures xsi:type="ecore:EReference" name="textfeld" lowerBound="1"
        eType="#//Textfeld" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ausgabefeld" lowerBound="1"
        eType="#//Ausgabefeld" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Textfeld">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="displayText" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Eingabefeld">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribut" lowerBound="1"
        eType="#//Attribut"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dateneingabefeld">
    <eStructuralFeatures xsi:type="ecore:EReference" name="eingabefeld" lowerBound="1"
        eType="#//Eingabefeld" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="textfeld" lowerBound="1"
        eType="#//Textfeld" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Ausgabefeld">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attribut" lowerBound="1"
        eType="#//Attribut"/>
  </eClassifiers>
</ecore:EPackage>
